{"uuid": "8f0e3454-31e3-42e6-9c66-b8bebb3f7f69", "counter": 44, "stdout": "\u001b[1;31mfatal: [inventory.ini]: UNREACHABLE! => {\u001b[0m\r\n\u001b[1;31m    \"changed\": false,\u001b[0m\r\n\u001b[1;31m    \"msg\": \"Failed to connect to the host via ssh: OpenSSH_9.9p2, OpenSSL 3.5.0 8 Apr 2025\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\\r\\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\\r\\ndebug1: Control socket \\\"/home/mcmxcviii/.ansible/cp/e40c06ec51\\\" does not exist\\r\\ndebug2: resolving \\\"inventory.ini\\\" port 22\\r\\ndebug3: resolve_host: lookup inventory.ini:22\\r\\nssh: Could not resolve hostname inventory.ini: Name or service not known\",\u001b[0m\r\n\u001b[1;31m    \"unreachable\": true\u001b[0m\r\n\u001b[1;31m}\u001b[0m", "start_line": 74, "end_line": 79, "runner_ident": "834bd8d7-4ce4-4c6c-972b-4936186f30f3", "event": "runner_on_unreachable", "pid": 428271, "created": "2025-04-12T21:02:57.632757+00:00", "parent_uuid": "38d57ae8-a7f1-a0ff-87a1-000000000004", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "a7e1e55a-c38d-4a6b-8b6b-834f63840782", "play": "Check server load", "play_uuid": "38d57ae8-a7f1-a0ff-87a1-000000000002", "play_pattern": "all", "task": "Get system load information", "task_uuid": "38d57ae8-a7f1-a0ff-87a1-000000000004", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:6", "host": "inventory.ini", "remote_addr": "inventory.ini", "start": "2025-04-12T21:02:57.582388+00:00", "end": "2025-04-12T21:02:57.632549+00:00", "duration": 0.050161, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: OpenSSH_9.9p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\r\ndebug1: Control socket \"/home/mcmxcviii/.ansible/cp/e40c06ec51\" does not exist\r\ndebug2: resolving \"inventory.ini\" port 22\r\ndebug3: resolve_host: lookup inventory.ini:22\r\nssh: Could not resolve hostname inventory.ini: Name or service not known", "changed": false}, "uuid": "8f0e3454-31e3-42e6-9c66-b8bebb3f7f69"}}