{"uuid": "b15a526a-4ccc-474f-87f3-a53d993d8ff9", "counter": 44, "stdout": "\u001b[1;31mfatal: [inventory.ini]: UNREACHABLE! => {\u001b[0m\r\n\u001b[1;31m    \"changed\": false,\u001b[0m\r\n\u001b[1;31m    \"msg\": \"Failed to connect to the host via ssh: OpenSSH_9.9p2, OpenSSL 3.5.0 8 Apr 2025\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\\r\\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\\r\\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\\r\\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\\r\\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\\r\\ndebug1: Control socket \\\"/home/mcmxcviii/.ansible/cp/e40c06ec51\\\" does not exist\\r\\ndebug2: resolving \\\"inventory.ini\\\" port 22\\r\\ndebug3: resolve_host: lookup inventory.ini:22\\r\\nssh: Could not resolve hostname inventory.ini: Name or service not known\",\u001b[0m\r\n\u001b[1;31m    \"unreachable\": true\u001b[0m\r\n\u001b[1;31m}\u001b[0m", "start_line": 74, "end_line": 79, "runner_ident": "bba310e6-d0e5-4b0e-87df-0c1d58872654", "event": "runner_on_unreachable", "pid": 428560, "created": "2025-04-12T21:03:17.558897+00:00", "parent_uuid": "38d57ae8-a7f1-6e44-4794-000000000004", "event_data": {"playbook": "playbook.yml", "playbook_uuid": "d949d561-abac-4f1e-a075-c7ae00bdc6a4", "play": "Check server load", "play_uuid": "38d57ae8-a7f1-6e44-4794-000000000002", "play_pattern": "all", "task": "Get system load information", "task_uuid": "38d57ae8-a7f1-6e44-4794-000000000004", "task_action": "command", "resolved_action": "ansible.builtin.command", "task_args": "", "task_path": "/home/mcmxcviii/Documents/gh1/pg_install/playbook.yml:6", "host": "inventory.ini", "remote_addr": "inventory.ini", "start": "2025-04-12T21:03:17.515989+00:00", "end": "2025-04-12T21:03:17.558736+00:00", "duration": 0.042747, "res": {"unreachable": true, "msg": "Failed to connect to the host via ssh: OpenSSH_9.9p2, OpenSSL 3.5.0 8 Apr 2025\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/20-systemd-ssh-proxy.conf\r\ndebug3: /etc/ssh/ssh_config line 2: Including file /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/30-libvirt-ssh-proxy.conf\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/mcmxcviii/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/mcmxcviii/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master at '/home/mcmxcviii/.ansible/cp/e40c06ec51'\r\ndebug1: Control socket \"/home/mcmxcviii/.ansible/cp/e40c06ec51\" does not exist\r\ndebug2: resolving \"inventory.ini\" port 22\r\ndebug3: resolve_host: lookup inventory.ini:22\r\nssh: Could not resolve hostname inventory.ini: Name or service not known", "changed": false}, "uuid": "b15a526a-4ccc-474f-87f3-a53d993d8ff9"}}